//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.FeeCollections = new HashSet<FeeCollection>();
        }
    
        public int CustomerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal EntryFee { get; set; }
        public decimal MonthlyCharge { get; set; }
        public int OutletID { get; set; }
        public int CusStatus { get; set; }
        public string Photopath { get; set; }
    
        public virtual Outlet Outlet { get; set; }
        public virtual ICollection<FeeCollection> FeeCollections { get; set; }
    }
}
