//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string ContactNo { get; set; }
        public string PresentAdd { get; set; }
        public string PermanentAdd { get; set; }
        public string Photopath { get; set; }
        public int DesignationID { get; set; }
    
        public virtual Designaiton Designaiton { get; set; }
    }
}
