//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollection
    {
        public FeeCollection()
        {
            this.FeeCollDetails = new HashSet<FeeCollDetail>();
        }
    
        public int FeeCollectionID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public int CustomerID { get; set; }
        public int OutletID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<FeeCollDetail> FeeCollDetails { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
