//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollDetail
    {
        public int FeeCollectionDetailsID { get; set; }
        public System.DateTime RecMonth { get; set; }
        public decimal FeeAmt { get; set; }
        public int FeeCollectionID { get; set; }
    
        public virtual FeeCollection FeeCollection { get; set; }
    }
}
