//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInformation
    {
        public int SystemInfoID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string TelephoneNo { get; set; }
        public string EamilAddress { get; set; }
        public string WebAdd { get; set; }
        public System.DateTime SystemStartDate { get; set; }
        public string EmpPhotoPath { get; set; }
        public string CusPhotoPath { get; set; }
        public string SuppPhotoPath { get; set; }
    }
}
